name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      #- name: Cache Android Virtual Device (AVD)
      #  id: avd-cache
      #  uses: actions/cache@v4
      #  with:
      #    path: |
      #      ~/.android/avd/*
      #      ~/.android/adb*
      #    key: avd
#
      #- name: Allow using Kernel-based Virtual Machine (KVM)
      #  # See recommendation at https://github.com/ReactiveCircus/android-emulator-runner
      #  # This solution accomplishes the same but more concisely
      #  run: sudo chmod 666 /dev/kvm
#
      #- name: Create AVD Snapshot for Caching
      #  if: steps.avd-cache.outputs.cache-hit != 'true'
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 28
      #    force-avd-creation: false
      #    emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #    script: echo "Generated AVD snapshot for caching."

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test
        
      #- name: Run Android Tests
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 28
      #    force-avd-creation: false
      #    emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #    script: ./gradlew connectedDebugAndroidTest

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info